// <auto-generated />
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace IronThorVG.Native;

internal static partial class ThorVGNative
{
    [LibraryImport(LibraryName, EntryPoint = "tvg_canvas_destroy")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_canvas_destroy_raw(nint canvas);

    [LibraryImport(LibraryName, EntryPoint = "tvg_paint_unref")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_paint_unref_raw(nint paint, [MarshalAs(UnmanagedType.I1)] bool free);

    [LibraryImport(LibraryName, EntryPoint = "tvg_gradient_del")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_gradient_del_raw(nint grad);

    [LibraryImport(LibraryName, EntryPoint = "tvg_saver_del")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_saver_del_raw(nint saver);

    [LibraryImport(LibraryName, EntryPoint = "tvg_animation_del")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_animation_del_raw(nint animation);

    [LibraryImport(LibraryName, EntryPoint = "tvg_accessor_del")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    internal static partial Result tvg_accessor_del_raw(nint accessor);
}
